# Generated by Django 6.0.1 on 2026-01-31 02:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberogumodoki', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserve_date',
            field=models.DateField(default=datetime.date(2026, 1, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='reserve_time',
            field=models.CharField(default='00:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='taberogumodoki.item'),
        ),
    ]
