# Generated by Django 6.0.1 on 2026-02-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberogumodoki', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
