# Generated by Django 6.0.2 on 2026-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_stripe_customer_id_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium_cancel_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
