"""
Django settings for config project.
 
Generated by 'django-admin startproject' using Django 3.1.4.
 
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
 
from pathlib import Path

import os
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 
# 本番環境用
#env.read_env(root('.env.prod'))
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG") == "True"
 
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "taberogumodoki-475f351d156f.herokuapp.com"
).split(",")

if not SECRET_KEY:
    raise ValueError("SECRET_KEY is not set")
 
# Application definition
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'taberogumodoki',  
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
 
ROOT_URLCONF = 'config.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 追記
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.custom_context_processors.base',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'config.wsgi.application'
 
 
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
 
 
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
 
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
 
LANGUAGE_CODE = 'ja'  
 
TIME_ZONE = 'Asia/Tokyo'  
 
USE_I18N = True
 
USE_L10N = True
 
USE_TZ = True
 
 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
 
STATIC_URL = '/static/'
 
STATICFILES_DIRS = [BASE_DIR / 'static']  # 追記
 
# 消費税率
TAX_RATE = 0.1
 
# Stripe API Key
STRIPE_API_SECRET_KEY = os.environ.get("STRIPE_API_SECRET_KEY")
# スキーマ＆ドメイン
MY_URL = os.environ.get("MY_URL")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET")
STRIPE_TAX_RATE_ID = os.environ.get("STRIPE_TAX_RATE_ID")
 
 
# カスタムユーザーモデル
AUTH_USER_MODEL = 'taberogumodoki.User'
 
LOGIN_URL = '/login/'
 
LOGIN_REDIRECT_URL = '/'
 
LOGOUT_REDIRECT_URL = '/login/'

TITLE = "NAGOYAMESHI"  # サイトのタイトル

STRIPE_PRICE_ID = 'price_1StHbY3bZq4CpP0cvBk0r7Iz'

STATIC_ROOT = BASE_DIR / 'staticfiles'


