# Generated by Django 6.0.2 on 2026-03-08 01:25

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', upload_to=restaurant.models.upload_image_to)),
            ],
        ),
    ]
