# Generated by Django 6.0.2 on 2026-04-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.PositiveIntegerField(default=0, max_length=50),
        ),
    ]
