# Generated by Django 6.0.2 on 2026-04-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
