# Generated by Django 6.0.2 on 2026-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_review_user_name_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
