# Generated by Django 6.0.2 on 2026-05-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restaurant_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='stripe_price_id',
        ),
    ]
