# Generated by Django 6.0.2 on 2026-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_restaurant_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='static_image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
